unit dev_mock_types;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils, fgl, fpjson, jsonparser;

type
  TGlobalOptions = class
  public
    TemporalCoherence: Boolean;
    SpatialCoherence: Boolean;
    MaxRecordsPerTable: Integer;
    AutoGenerateDependencies: Boolean;
    ForceRegenerateDependencies: Boolean;
    AutoGenerateDescendants: Boolean;
    OutputDir: string;
  end;

  { TSchemaRef }

  TSchemaRef = class
  public
    Name: string;
    FileName: string;
    DefaultCount: Integer;
    MaxCount: Integer;
    Dependencies: TStringList;
    OutputFiles: TStringList;
    constructor Create;
    destructor Destroy; override;
  end;

  TSchemaRefList = specialize TFPGObjectList<TSchemaRef>;

  { TRepositoryRef }

  TRepositoryRef = class
  public
    Name: string;
    FileName: string;
    RepoType: string; // "array" or "objects"
    Fields: TStringList;
    constructor Create;
    destructor Destroy; override;
  end;

  TRepositoryRefList = specialize TFPGObjectList<TRepositoryRef>;

  { TGeneratorConfig }

  TGeneratorConfig = class
  public
    Version: Integer;
    GenerationOrder: TStringList;
    GlobalOptions: TGlobalOptions;
    Schemas: TSchemaRefList;
    Repositories: TRepositoryRefList;

    constructor Create;
    destructor Destroy; override;

    function GetSchemaByName(const AName: String): TSchemaRef;
    procedure LoadFromJSON(const FileName: string);
    procedure Validate;
  end;

  TRelations = class
  public
    Parent: string;
    ParentKey: string;
    ForeignKey: string;
    OptionalParent: Boolean;
    MinChildren: Integer;
    MaxChildren: Integer;
  end;

  { TPolymorphic }

  TPolymorphic = class
  public
    TableField: string;
    IdField: string;
    AllowedTables: TStringList;
    constructor Create;
    destructor Destroy; override;
  end;

  THierarchyLevel = class
  public
    Rank: string;
    Min: Integer;
    Max: Integer;
    Source: string;
  end;

  THierarchyLevelList = specialize TFPGObjectList<THierarchyLevel>;

  { THierarchy }

  THierarchy = class
  public
    RankField: string;
    ParentField: string;
    Levels: THierarchyLevelList;
    constructor Create;
    destructor Destroy; override;
  end;

  { TExternalSource }

  TExternalSource = class
  public
    Name: string;
    FileName: string;
    CountryField: string;
    StateField: string;
    CityField: string;
    AllowedCountries: TStringList;
    LocalitiesSource: string;
    constructor Create;
    destructor Destroy; override;
  end;

  TExternalSourceList = specialize TFPGObjectList<TExternalSource>;

  { TColumnArgs }

  TColumnArgs = class
  public
    Raw: TStringList; // store raw key=value for flexibility
    constructor Create;
    destructor Destroy; override;
  end;

  TColumn = class
  public
    Name: string;
    DataType: string;
    AutoIncrement: Boolean;
    Unique: Boolean;
    GenerationMode: string;
    StartAt: Integer;
    IncrementBy: Integer;
    Nullable: Boolean;
    DefaultValue: string;
    FixedValue: string;
    Ignore: Boolean;
    EnumValues: TStringList;
    Multiple: Boolean;
    Weights: TStringList;
    RangeMin: string;
    RangeMax: string;
    Mask: string;
    Source: string;
    SourceTable: string;
    SourceField: string;
    FilterBy: TStringList;
    Func: string;
    Args: TColumnArgs;
    DependsOn: TStringList;

    constructor Create;
    destructor Destroy; override;
  end;

  TColumnList = specialize TFPGObjectList<TColumn>;

  { TTableSchema }

  TTableSchema = class
  public
    TableName: string;
    Relations: TRelations;
    Polymorphic: TPolymorphic;
    Hierarchy: THierarchy;
    ExternalSources: TExternalSourceList;
    Columns: TColumnList;

    constructor Create;
    destructor Destroy; override;

    procedure LoadFromJSON(const FileName: string);
    procedure Validate;
  end;

  TStringListMap = specialize TFPGMap<string, TStringList>;

  { TTableDependencyResolver }

  TTableDependencyResolver = class
  private
    FGraph: TStringListMap;
    FInDegree: specialize TFPGMap<string, Integer>;
    procedure AddEdge(const FromTable, ToTable: string);
  public
    constructor Create;
    destructor Destroy; override;

    function Resolve(Config: TGeneratorConfig): TStringList;
  end;

  { TColumnDependencyResolver }

  TColumnDependencyResolver = class
  private
    FGraph: TStringListMap;
    FInDegree: specialize TFPGMap<string, Integer>;
    procedure AddEdge(const FromCol, ToCol: string);
  public
    constructor Create;
    destructor Destroy; override;

    function Resolve(Schema: TTableSchema): TStringList;
  end;

  { TMockDataGenerator }

  TMockDataGenerator = class
  private
    FConfig: TGeneratorConfig;
    FSchemas: specialize TFPGMap<string, TTableSchema>;
    FValueGen: TValueGenerator;

    procedure LoadSchemas;
    function ResolveTableOrder: TStringList;
    function ResolveColumnOrder(ASchema: TTableSchema): TStringList;

    function GenerateColumnValue(Col: TColumn; Row: TStringList; Schema: TTableSchema): string;
    procedure GenerateTable(const Schema: TTableSchema; const OutputFile: string);
  public
    constructor Create;
    destructor Destroy; override;

    procedure LoadConfig(const FileName: string);
    procedure GenerateAll;
  end;

  procedure Require(const Condition: Boolean; const Msg: string);
  procedure RequireNonEmpty(const S, FieldName: string);
  procedure RequireInSet(const S, FieldName: string; const Allowed: array of string);
  procedure RequireRangeInt(Value, Min, Max: Integer; const FieldName: string);


implementation

procedure Require(const Condition: Boolean; const Msg: string);
begin
  if not Condition then
    raise Exception.Create('Validation error: ' + Msg);
end;

procedure RequireNonEmpty(const S, FieldName: string);
begin
  if Trim(S) = '' then
    raise Exception.Create('Validation error: field "' + FieldName + '" cannot be empty.');
end;

procedure RequireInSet(const S, FieldName: string; const Allowed: array of string);
var
  i: Integer;
begin
  for i := 0 to High(Allowed) do
    if SameText(S, Allowed[i]) then Exit;

  raise Exception.CreateFmt(
    'Validation error: field "%s" has invalid value "%s". Allowed: %s',
    [FieldName, S, String.Join(', ', Allowed)]
  );
end;

procedure RequireRangeInt(Value, Min, Max: Integer; const FieldName: string);
begin
  if (Value < Min) or (Value > Max) then
    raise Exception.CreateFmt(
      'Validation error: field "%s" must be between %d and %d (got %d)',
      [FieldName, Min, Max, Value]
    );
end;

{ TSchemaRef }

constructor TSchemaRef.Create;
begin
  Dependencies := TStringList.Create;
  OutputFiles := TStringList.Create;
end;

destructor TSchemaRef.Destroy;
begin
  Dependencies.Free;
  OutputFiles.Free;
  inherited Destroy;
end;

{ TRepositoryRef }

constructor TRepositoryRef.Create;
begin
  Fields := TStringList.Create;
end;

destructor TRepositoryRef.Destroy;
begin
  Fields.Free;
  inherited Destroy;
end;

{ TGeneratorConfig }

constructor TGeneratorConfig.Create;
begin
  GenerationOrder := TStringList.Create;
  GlobalOptions := TGlobalOptions.Create;
  Schemas := TSchemaRefList.Create(True);
  Repositories := TRepositoryRefList.Create(True);
end;

destructor TGeneratorConfig.Destroy;
begin
  GenerationOrder.Free;
  GlobalOptions.Free;
  Schemas.Free;
  Repositories.Free;
  inherited Destroy;
end;

function TGeneratorConfig.GetSchemaByName(const AName: String): TSchemaRef;
begin
  Result := nil;

  for i := 0 to Schemas.Count - 1 do
  begin
    if SameText(Schemas.Items[i].Name, AName) then
    begin
      Result := Schemas.Items[i];
      Break;
    end;
  end;
end;

procedure TGeneratorConfig.LoadFromJSON(const FileName: string);
var
  JSON: TJSONData;
  Obj: TJSONObject;
  Arr: TJSONArray;
  Item: TJSONData;
  SRef: TSchemaRef;
  RRef: TRepositoryRef;
  i, j: Integer;
begin
  JSON := GetJSON(ReadFileToString(FileName));
  Obj := TJSONObject(JSON);

  { version }
  Version := Obj.Get('version', 1);

  { generationOrder }
  GenerationOrder.Clear;
  Arr := Obj.Arrays['generationOrder'];
  for i := 0 to Arr.Count - 1 do
    GenerationOrder.Add(Arr.Strings[i]);

  { globalOptions }
  with GlobalOptions do
  begin
    TemporalCoherence := Obj.Objects['globalOptions'].Get('temporalCoherence', True);
    SpatialCoherence := Obj.Objects['globalOptions'].Get('spatialCoherence', True);
    MaxRecordsPerTable := Obj.Objects['globalOptions'].Get('maxRecordsPerTable', 10000);
    AutoGenerateDependencies := Obj.Objects['globalOptions'].Get('autoGenerateDependencies', True);
    ForceRegenerateDependencies := Obj.Objects['globalOptions'].Get('forceRegenerateDependencies', False);
    AutoGenerateDescendants := Obj.Objects['globalOptions'].Get('autoGenerateDescendants', True);
    OutputDir := Obj.Objects['globalOptions'].Get('outputDir', './output');
  end;

  { schemas }
  Schemas.Clear;
  Arr := Obj.Arrays['schemas'];
  for i := 0 to Arr.Count - 1 do
  begin
    Item := Arr.Items[i];
    SRef := TSchemaRef.Create;

    SRef.Name := Item.FindPath('name').AsString;
    SRef.FileName := Item.FindPath('file').AsString;
    SRef.DefaultCount := Item.FindPath('defaultCount').AsInteger;
    SRef.MaxCount := Item.FindPath('maxCount').AsInteger;

    { dependencies }
    if Item.FindPath('dependencies') <> nil then
      for j := 0 to Item.FindPath('dependencies').Count - 1 do
        SRef.Dependencies.Add(Item.FindPath('dependencies').Items[j].AsString);

    { outputFiles }
    if Item.FindPath('outputFiles') <> nil then
      for j := 0 to Item.FindPath('outputFiles').Count - 1 do
        SRef.OutputFiles.Add(Item.FindPath('outputFiles').Items[j].AsString);

    Schemas.Add(SRef);
  end;

  { repositories }
  Repositories.Clear;
  Arr := Obj.Arrays['repositories'];
  for i := 0 to Arr.Count - 1 do
  begin
    Item := Arr.Items[i];
    RRef := TRepositoryRef.Create;

    RRef.Name := Item.FindPath('name').AsString;
    RRef.FileName := Item.FindPath('file').AsString;
    RRef.RepoType := Item.FindPath('type').AsString;

    if Item.FindPath('fields') <> nil then
      for j := 0 to Item.FindPath('fields').Count - 1 do
        RRef.Fields.Add(Item.FindPath('fields').Items[j].AsString);

    Repositories.Add(RRef);
  end;

  JSON.Free;
end;

procedure TGeneratorConfig.Validate;
var
  i: Integer;
  S: TSchemaRef;
  R: TRepositoryRef;
begin
  Require(Version >= 1, 'version must be >= 1');
  Require(GenerationOrder.Count > 0, 'generationOrder cannot be empty');

  { Validate schemas }
  for i := 0 to Schemas.Count - 1 do
  begin
    S := Schemas[i];

    RequireNonEmpty(S.Name, 'schemas[' + IntToStr(i) + '].name');
    RequireNonEmpty(S.FileName, 'schemas[' + IntToStr(i) + '].file');
    RequireRangeInt(S.DefaultCount, 0, S.MaxCount, 'defaultCount');
    RequireRangeInt(S.MaxCount, 0, 10000000, 'maxCount');
  end;

  { Validate repositories }
  for i := 0 to Repositories.Count - 1 do
  begin
    R := Repositories[i];

    RequireNonEmpty(R.Name, 'repositories[' + IntToStr(i) + '].name');
    RequireNonEmpty(R.FileName, 'repositories[' + IntToStr(i) + '].file');
    RequireInSet(R.RepoType, 'repositories[' + IntToStr(i) + '].type',
      ['array', 'objects']);
  end;

  { Validate generationOrder references }
  for i := 0 to GenerationOrder.Count - 1 do
    Require(
      Schemas.IndexOfName(GenerationOrder[i]) <> -1,
      'generationOrder references unknown schema "' + GenerationOrder[i] + '"'
    );
end;

{ TPolymorphic }

constructor TPolymorphic.Create;
begin
  AllowedTables := TStringList.Create;
end;

destructor TPolymorphic.Destroy;
begin
  AllowedTables.Free;
  inherited Destroy;
end;

{ THierarchy }

constructor THierarchy.Create;
begin
  Levels := THierarchyLevelList.Create(True);
end;

destructor THierarchy.Destroy;
begin
  Levels.Free;
  inherited Destroy;
end;

{ TExternalSource }

constructor TExternalSource.Create;
begin
  AllowedCountries := TStringList.Create;
end;

destructor TExternalSource.Destroy;
begin
  AllowedCountries.Free;
  inherited Destroy;
end;

{ TColumnArgs }

constructor TColumnArgs.Create;
begin
  Raw := TStringList.Create;
end;

destructor TColumnArgs.Destroy;
begin
  Raw.Free;
  inherited Destroy;
end;

constructor TColumn.Create;
begin
  EnumValues := TStringList.Create;
  Weights := TStringList.Create;
  FilterBy := TStringList.Create;
  DependsOn := TStringList.Create;
  Args := TColumnArgs.Create;
end;

destructor TColumn.Destroy;
begin
  EnumValues.Free;
  Weights.Free;
  FilterBy.Free;
  DependsOn.Free;
  Args.Free;
  inherited Destroy;
end;

{ TTableSchema }

constructor TTableSchema.Create;
begin
  Relations := TRelations.Create;
  Polymorphic := TPolymorphic.Create;
  Hierarchy := THierarchy.Create;
  ExternalSources := TExternalSourceList.Create(True);
  Columns := TColumnList.Create(True);
end;

destructor TTableSchema.Destroy;
begin
  Relations.Free;
  Polymorphic.Free;
  Hierarchy.Free;
  ExternalSources.Free;
  Columns.Free;
  inherited Destroy;
end;

procedure TTableSchema.LoadFromJSON(const FileName: string);
var
  JSON: TJSONData;
  Obj, Sub: TJSONObject;
  Arr: TJSONArray;
  i, j: Integer;
  Col: TColumn;
  Ext: TExternalSource;
  Lev: THierarchyLevel;
begin
  JSON := GetJSON(ReadFileToString(FileName));
  Obj := TJSONObject(JSON);

  { table }
  TableName := Obj.Get('table', '');

  { relations }
  if Obj.Find('relations') <> nil then
  begin
    Sub := Obj.Objects['relations'];
    Relations.Parent := Sub.Get('parent', '');
    Relations.ParentKey := Sub.Get('parentKey', '');
    Relations.ForeignKey := Sub.Get('foreignKey', '');
    Relations.OptionalParent := Sub.Get('optionalParent', False);
    Relations.MinChildren := Sub.Get('minChildren', 0);
    Relations.MaxChildren := Sub.Get('maxChildren', 10);
  end;

  { polymorphic }
  if Obj.Find('polymorphic') <> nil then
  begin
    Sub := Obj.Objects['polymorphic'];
    Polymorphic.TableField := Sub.Get('tableField', '');
    Polymorphic.IdField := Sub.Get('idField', '');

    Polymorphic.AllowedTables.Clear;
    Arr := Sub.Arrays['allowedTables'];
    for i := 0 to Arr.Count - 1 do
      Polymorphic.AllowedTables.Add(Arr.Strings[i]);
  end;

  { hierarchy }
  if Obj.Find('hierarchy') <> nil then
  begin
    Sub := Obj.Objects['hierarchy'];
    Hierarchy.RankField := Sub.Get('rankField', '');
    Hierarchy.ParentField := Sub.Get('parentField', '');

    Hierarchy.Levels.Clear;
    Arr := Sub.Arrays['levels'];
    for i := 0 to Arr.Count - 1 do
    begin
      Lev := THierarchyLevel.Create;
      Lev.Rank := Arr.Objects[i].Get('rank', '');
      Lev.Min := Arr.Objects[i].Get('min', 0);
      Lev.Max := Arr.Objects[i].Get('max', 0);
      Lev.Source := Arr.Objects[i].Get('source', '');
      Hierarchy.Levels.Add(Lev);
    end;
  end;

  { externalSource }
  if Obj.Find('externalSource') <> nil then
  begin
    ExternalSources.Clear;
    Sub := Obj.Objects['externalSource'];

    for i := 0 to Sub.Count - 1 do
    begin
      Ext := TExternalSource.Create;
      Ext.Name := Sub.Names[i];

      with Sub.Objects[Ext.Name] do
      begin
        Ext.FileName := Get('file', '');
        Ext.CountryField := Get('countryField', '');
        Ext.StateField := Get('stateField', '');
        Ext.CityField := Get('cityField', '');
        Ext.LocalitiesSource := Get('localitiesSource', '');

        if Find('allowedCountries') <> nil then
        begin
          Arr := Arrays['allowedCountries'];
          for j := 0 to Arr.Count - 1 do
            Ext.AllowedCountries.Add(Arr.Strings[j]);
        end;
      end;

      ExternalSources.Add(Ext);
    end;
  end;

  { columns }
  Columns.Clear;
  Arr := Obj.Arrays['columns'];

  for i := 0 to Arr.Count - 1 do
  begin
    Sub := Arr.Objects[i];
    Col := TColumn.Create;

    Col.Name := Sub.Get('name', '');
    Col.DataType := Sub.Get('type', '');
    Col.AutoIncrement := Sub.Get('autoIncrement', False);
    Col.Unique := Sub.Get('unique', False);
    Col.GenerationMode := Sub.Get('generationMode', '');
    Col.StartAt := Sub.Get('startAt', 1);
    Col.IncrementBy := Sub.Get('incrementBy', 1);
    Col.Nullable := Sub.Get('nullable', False);
    Col.DefaultValue := Sub.Get('default', '');
    Col.FixedValue := Sub.Get('fixed', '');
    Col.Ignore := Sub.Get('ignore', False);
    Col.Mask := Sub.Get('mask', '');
    Col.Source := Sub.Get('source', '');
    Col.SourceTable := Sub.Get('sourceTable', '');
    Col.SourceField := Sub.Get('sourceField', '');

    { enum }
    if Sub.Find('enum') <> nil then
    begin
      Arr := Sub.Arrays['enum'];
      for j := 0 to Arr.Count - 1 do
        Col.EnumValues.Add(Arr.Items[j].AsString);
    end;

    { weights }
    if Sub.Find('weights') <> nil then
    begin
      Arr := Sub.Arrays['weights'];
      for j := 0 to Arr.Count - 1 do
        Col.Weights.Add(FloatToStr(Arr.Items[j].AsFloat));
    end;

    { range }
    if Sub.Find('range') <> nil then
    begin
      Col.RangeMin := Sub.Arrays['range'].Items[0].AsString;
      Col.RangeMax := Sub.Arrays['range'].Items[1].AsString;
    end;

    { filterBy }
    if Sub.Find('filterBy') <> nil then
    begin
      for j := 0 to Sub.Objects['filterBy'].Count - 1 do
        Col.FilterBy.Add(Sub.Objects['filterBy'].Names[j] + '=' +
                         Sub.Objects['filterBy'].Items[j].AsString);
    end;

    { function + args }
    Col.Func := Sub.Get('function', '');

    if Sub.Find('args') <> nil then
    begin
      for j := 0 to Sub.Objects['args'].Count - 1 do
        Col.Args.Raw.Add(Sub.Objects['args'].Names[j] + '=' +
                         Sub.Objects['args'].Items[j].AsString);
    end;

    { dependsOn }
    if Sub.Find('dependsOn') <> nil then
    begin
      Arr := Sub.Arrays['dependsOn'];
      for j := 0 to Arr.Count - 1 do
        Col.DependsOn.Add(Arr.Strings[j]);
    end;

    Columns.Add(Col);
  end;

  JSON.Free;
end;

procedure TTableSchema.Validate;
var
  i: Integer;
  Col: TColumn;
  Ext: TExternalSource;
begin
  RequireNonEmpty(TableName, 'table');

  { Validate relations }
  if Relations.Parent <> '' then
  begin
    RequireNonEmpty(Relations.ParentKey, 'relations.parentKey');
    RequireNonEmpty(Relations.ForeignKey, 'relations.foreignKey');
  end;

  { Validate polymorphic }
  if Polymorphic.TableField <> '' then
  begin
    RequireNonEmpty(Polymorphic.IdField, 'polymorphic.idField');
    Require(Polymorphic.AllowedTables.Count > 0,
      'polymorphic.allowedTables cannot be empty');
  end;

  { Validate hierarchy }
  if Hierarchy.RankField <> '' then
  begin
    RequireNonEmpty(Hierarchy.ParentField, 'hierarchy.parentField');
    Require(Hierarchy.Levels.Count > 0, 'hierarchy.levels cannot be empty');
  end;

  { Validate external sources }
  for i := 0 to ExternalSources.Count - 1 do
  begin
    Ext := ExternalSources[i];
    RequireNonEmpty(Ext.FileName, 'externalSource[' + Ext.Name + '].file');
  end;

  { Validate columns }
  Require(Columns.Count > 0, 'columns cannot be empty');

  for i := 0 to Columns.Count - 1 do
  begin
    Col := Columns[i];

    RequireNonEmpty(Col.Name, 'columns[' + IntToStr(i) + '].name');
    RequireInSet(Col.DataType, 'columns[' + IntToStr(i) + '].type',
      ['integer', 'float', 'string', 'boolean', 'date', 'datetime']);

    if Col.GenerationMode <> '' then
      RequireInSet(Col.GenerationMode, 'generationMode',
        ['random', 'sequential', 'incremental', 'conditional', 'template', 'list']);

    if Col.EnumValues.Count > 0 then
      Require(Col.Weights.Count = 0
        or (Col.Weights.Count = Col.EnumValues.Count),
        'weights must match enum length');

    if (Col.SourceTable <> '') xor (Col.SourceField <> '') then
      raise Exception.Create('sourceTable and sourceField must be used together');

    if Col.RangeMin <> '' then
      Require(Col.RangeMax <> '', 'range must have two values');
  end;
end;

{ TTableDependencyResolver }

constructor TTableDependencyResolver.Create;
begin
  FGraph := TStringListMap.Create;
  FInDegree := specialize TFPGMap<string, Integer>.Create;
end;

procedure TTableDependencyResolver.AddEdge(const FromTable, ToTable: string);
var
  L: TStringList;
begin
  if not FGraph.TryGetData(FromTable, L) then
  begin
    L := TStringList.Create;
    FGraph.Add(FromTable, L);
  end;
  L.Add(ToTable);
end;

destructor TTableDependencyResolver.Destroy;
var
  i: Integer;
begin
  for i := 0 to FGraph.Count - 1 do
    FGraph.Data[i].Free;
  FGraph.Free;
  FInDegree.Free;
  inherited Destroy;
end;

function TTableDependencyResolver.Resolve(Config: TGeneratorConfig): TStringList;
var
  i, j: Integer;
  S: TSchemaRef;
  Dep: string;
  Queue: TStringList;
  Node, Neighbor: string;
  L: TStringList;
begin
  Result := TStringList.Create;

  { Inicializa in-degree }
  for i := 0 to Config.Schemas.Count - 1 do
  begin
    S := Config.Schemas[i];
    FInDegree.Add(S.Name, 0);
  end;

  { Constrói o grafo }
  for i := 0 to Config.Schemas.Count - 1 do
  begin
    S := Config.Schemas[i];
    for j := 0 to S.Dependencies.Count - 1 do
    begin
      Dep := S.Dependencies[j];

      if FInDegree.IndexOf(Dep) = -1 then
        raise Exception.Create('Unknown dependency: ' + Dep);

      AddEdge(Dep, S.Name);
      FInDegree[S.Name] := FInDegree[S.Name] + 1;
    end;
  end;

  { Kahn's algorithm }
  Queue := TStringList.Create;
  try
    for i := 0 to FInDegree.Count - 1 do
      if FInDegree.Data[i] = 0 then
        Queue.Add(FInDegree.Keys[i]);

    while Queue.Count > 0 do
    begin
      Node := Queue[0];
      Queue.Delete(0);
      Result.Add(Node);

      if FGraph.TryGetData(Node, L) then
      begin
        for Neighbor in L do
        begin
          FInDegree[Neighbor] := FInDegree[Neighbor] - 1;
          if FInDegree[Neighbor] = 0 then
            Queue.Add(Neighbor);
        end;
      end;
    end;

    if Result.Count <> FInDegree.Count then
      raise Exception.Create('Cycle detected in table dependencies.');
  finally
    Queue.Free;
  end;
end;

{ TColumnDependencyResolver }

constructor TColumnDependencyResolver.Create;
begin
  FGraph := TStringListMap.Create;
  FInDegree := specialize TFPGMap<string, Integer>.Create;
end;

procedure TColumnDependencyResolver.AddEdge(const FromCol, ToCol: string);
var
  L: TStringList;
begin
  if not FGraph.TryGetData(FromCol, L) then
  begin
    L := TStringList.Create;
    FGraph.Add(FromCol, L);
  end;
  L.Add(ToCol);
end;

destructor TColumnDependencyResolver.Destroy;
var
  i: Integer;
begin
  for i := 0 to FGraph.Count - 1 do
    FGraph.Data[i].Free;
  FGraph.Free;
  FInDegree.Free;
  inherited Destroy;
end;

function TColumnDependencyResolver.Resolve(Schema: TTableSchema): TStringList;
var
  i, j: Integer;
  Col: TColumn;
  Dep: string;
  Queue: TStringList;
  Node, Neighbor: string;
  L: TStringList;
begin
  Result := TStringList.Create;

  { Inicializa in-degree }
  for i := 0 to Schema.Columns.Count - 1 do
  begin
    Col := Schema.Columns[i];
    FInDegree.Add(Col.Name, 0);
  end;

  { Constrói o grafo }
  for i := 0 to Schema.Columns.Count - 1 do
  begin
    Col := Schema.Columns[i];

    for j := 0 to Col.DependsOn.Count - 1 do
    begin
      Dep := Col.DependsOn[j];

      if FInDegree.IndexOf(Dep) = -1 then
        raise Exception.CreateFmt(
          'Column "%s" depends on unknown column "%s"',
          [Col.Name, Dep]
        );

      AddEdge(Dep, Col.Name);
      FInDegree[Col.Name] := FInDegree[Col.Name] + 1;
    end;
  end;

  { Kahn's algorithm }
  Queue := TStringList.Create;
  try
    for i := 0 to FInDegree.Count - 1 do
      if FInDegree.Data[i] = 0 then
        Queue.Add(FInDegree.Keys[i]);

    while Queue.Count > 0 do
    begin
      Node := Queue[0];
      Queue.Delete(0);
      Result.Add(Node);

      if FGraph.TryGetData(Node, L) then
      begin
        for Neighbor in L do
        begin
          FInDegree[Neighbor] := FInDegree[Neighbor] - 1;
          if FInDegree[Neighbor] = 0 then
            Queue.Add(Neighbor);
        end;
      end;
    end;

    if Result.Count <> FInDegree.Count then
      raise Exception.Create('Cycle detected in column dependencies.');
  finally
    Queue.Free;
  end;
end;

{ TMockDataGenerator }

constructor TMockDataGenerator.Create;
begin
  FConfig := nil;
  FSchemas := specialize TFPGMap<string, TTableSchema>.Create;
  FValueGen := nil;
end;

destructor TMockDataGenerator.Destroy;
var
  i: Integer;
begin
  for i := 0 to FSchemas.Count - 1 do
    FSchemas.Data[i].Free;
  FSchemas.Free;
  FConfig.Free;
  FValueGen.Free;
  inherited Destroy;
end;

procedure TMockDataGenerator.GenerateAll;
var
  Order: TStringList;
  i: Integer;
  TableName: string;
  Schema: TTableSchema;
  SRef: TSchemaRef;
begin
  Order := ResolveTableOrder;
  try
    for i := 0 to Order.Count - 1 do
    begin
      TableName := Order[i];
      Schema := FSchemas[TableName];
      SRef := FConfig.Schemas[FConfig.Schemas.IndexOfName(TableName)];

      if SRef.OutputFiles.Count = 0 then
        GenerateTable(Schema, FConfig.GlobalOptions.OutputDir + '/' + TableName + '.csv')
      else
        GenerateTable(Schema, FConfig.GlobalOptions.OutputDir + '/' + SRef.OutputFiles[0]);
    end;
  finally
    Order.Free;
  end;
end;

function TMockDataGenerator.GenerateColumnValue(Col: TColumn; Row: TStringList; Schema: TTableSchema): string;
begin
  Result := FValueGen.Generate(Col, Row, Schema);
end;

procedure TMockDataGenerator.GenerateTable(const Schema: TTableSchema; const OutputFile: string);
var
  ColOrder: TStringList;
  Exporter: ITableExporter;
  Headers: array of string;
  Values: array of string;
  Row: TStringList;
  GeneratedRows: array of TStringList;
  i, c: Integer;
  Count: Integer;
begin
  ColOrder := ResolveColumnOrder(Schema);
  try
    Count := FConfig.GetSchemaByName(Schema.TableName).MaxCount;

    SetLength(Headers, ColOrder.Count);
    SetLength(Values, ColOrder.Count);
    SetLength(GeneratedRows, Count);

    for i := 0 to ColOrder.Count - 1 do
      Headers[i] := ColOrder[i];

    Exporter := CreateExporter(efCSV, Schema.TableName);
    Exporter.Open(OutputFile, Headers);

    for i := 0 to Count - 1 do
    begin
      Row := TStringList.Create;
      Row.NameValueSeparator := '=';
      GeneratedRows[i] := Row;

      for c := 0 to ColOrder.Count - 1 do
      begin
        Values[c] := GenerateColumnValue(
          Schema.Columns[ColOrder[c]],
          Row,
          Schema
        );
        Row.Values[ColOrder[c]] := Values[c];
      end;

      Exporter.WriteRow(Values);
    end;

    Exporter.Close;

    FValueGen.RegisterTableData(Schema.TableName, GeneratedRows);

  finally
    ColOrder.Free;
  end;
end;

procedure TMockDataGenerator.LoadConfig(const FileName: string);
begin
  if Assigned(FConfig) then
    FreeAndNil(FConfig);

  FConfig := TGeneratorConfig.Create;
  FConfig.LoadFromJSON(FileName);
  FConfig.Validate;

  LoadSchemas;

  FreeAndNil(FValueGen);
  FValueGen := TValueGenerator.Create(FConfig);
end;

procedure TMockDataGenerator.LoadSchemas;
var
  i: Integer;
  SRef: TSchemaRef;
  Schema: TTableSchema;
begin
  FSchemas.Clear;

  for i := 0 to FConfig.Schemas.Count - 1 do
  begin
    SRef := FConfig.Schemas[i];

    Schema := TTableSchema.Create;
    Schema.LoadFromJSON(SRef.FileName);
    Schema.Validate;

    FSchemas.Add(SRef.Name, Schema);
  end;
end;

function TMockDataGenerator.ResolveColumnOrder(ASchema: TTableSchema): TStringList;
var
  Resolver: TColumnDependencyResolver;
begin
  Resolver := TColumnDependencyResolver.Create;
  try
    Result := Resolver.Resolve(ASchema);
  finally
    Resolver.Free;
  end;
end;

function TMockDataGenerator.ResolveTableOrder: TStringList;
var
  Resolver: TTableDependencyResolver;
begin
  Resolver := TTableDependencyResolver.Create;
  try
    Result := Resolver.Resolve(FConfig);
  finally
    Resolver.Free;
  end;
end;

end.

